# Site settings
title: Caro-Oviedo
email: carolina.u.oviedo@gmail.com
description: 
baseurl: "/aboutMe" # the subpath of your site, e.g. /blog
url: "https://caro-oviedo.github.io" # the base hostname & protocol for your site

# Identity
your-name: Carolnina Oviedo
your-title: ESL Teacher | Translator | Software Development Trainee

# Social settings
500px_url:
facebook_url: 
github_url: 
gitlab_url: https://github.com/caro-oviedo
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Caro_Oviedo_

# Build settings
markdown: kramdown
